package telas;

import javax.swing.JOptionPane;
import model.metodos;

public class telaLogin extends javax.swing.JFrame {
    
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLogin = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        lUsuario = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        tSenha = new javax.swing.JPasswordField();
        bEntrarLogin = new javax.swing.JButton();
        bCadastrarLogin = new javax.swing.JButton();
        tUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pLogin.setBackground(new java.awt.Color(211, 242, 238));
        pLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pLogin.setToolTipText("");

        lLogin.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lLogin.setForeground(new java.awt.Color(0, 0, 0));
        lLogin.setText("Faça seu login");

        lUsuario.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lUsuario.setText("Usuário:");

        lSenha.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lSenha.setForeground(new java.awt.Color(0, 0, 0));
        lSenha.setText("Senha:");

        bEntrarLogin.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bEntrarLogin.setText("Entrar");
        bEntrarLogin.setVerifyInputWhenFocusTarget(false);
        bEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarLoginActionPerformed(evt);
            }
        });

        bCadastrarLogin.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bCadastrarLogin.setText("Cadastrar");
        bCadastrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCadastrarLoginMouseClicked(evt);
            }
        });
        bCadastrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarLoginActionPerformed(evt);
            }
        });

        tUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lLogin)
                .addGap(125, 125, 125))
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pLoginLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(lUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lSenha)
                                .addGap(28, 28, 28)))
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tUsuario)))
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bEntrarLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCadastrarLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lLogin)
                .addGap(79, 79, 79)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsuario)
                    .addComponent(tUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSenha))
                .addGap(88, 88, 88)
                .addComponent(bEntrarLogin)
                .addGap(18, 18, 18)
                .addComponent(bCadastrarLogin)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarLoginActionPerformed
        String usuario, senha;
        usuario = tUsuario.getText();
        senha = new String(tSenha.getPassword());
        metodos model = new metodos();
        String cnpjLogado = model.validaLogin(usuario, senha);    
        if (cnpjLogado != null) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaMenu(cnpjLogado).setVisible(true);
            }
        });
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário e/ou senha inválido!");
        }    

    }//GEN-LAST:event_bEntrarLoginActionPerformed

    private void bCadastrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarLoginActionPerformed

    }//GEN-LAST:event_bCadastrarLoginActionPerformed

    private void bCadastrarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCadastrarLoginMouseClicked
        telaCadastroLogin pi = new telaCadastroLogin();/*abre telaCadastroLogin*/
        pi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bCadastrarLoginMouseClicked

    private void tUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrarLogin;
    private javax.swing.JButton bEntrarLogin;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lUsuario;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPasswordField tSenha;
    private javax.swing.JTextField tUsuario;
    // End of variables declaration//GEN-END:variables
}
