package telas;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import model.metodos;
import model.usuario;

public class telaMeusdados extends javax.swing.JFrame {
    
    public void fecharJanela(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private Integer codigo;

    /**
     * Creates new form NewJFrame
     */
    public telaMeusdados() {
        initComponents();
    }
    
    public telaMeusdados(Integer id) {
        initComponents();
        this.codigo = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMeusdados = new javax.swing.JPanel();
        lMeusdados = new javax.swing.JLabel();
        bAtualizardados = new javax.swing.JButton();
        bExcluirdados = new javax.swing.JButton();
        tSenhaDados = new javax.swing.JPasswordField();
        lSenhaDados = new javax.swing.JLabel();
        lEmailDados = new javax.swing.JLabel();
        tEmailDados = new javax.swing.JPasswordField();
        tTelefoneDados = new javax.swing.JPasswordField();
        lTelefoneDados = new javax.swing.JLabel();
        lCnpjDados = new javax.swing.JLabel();
        tCnpjDados = new javax.swing.JPasswordField();
        tEmpresaDados = new javax.swing.JPasswordField();
        lEmpresaDados = new javax.swing.JLabel();
        bVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pMeusdados.setBackground(new java.awt.Color(211, 242, 238));
        pMeusdados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pMeusdados.setToolTipText("");

        lMeusdados.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lMeusdados.setForeground(new java.awt.Color(0, 0, 0));
        lMeusdados.setText("Meus dados");

        bAtualizardados.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bAtualizardados.setText("Atualizar dados");
        bAtualizardados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizardadosActionPerformed(evt);
            }
        });

        bExcluirdados.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bExcluirdados.setText("Excluir conta");
        bExcluirdados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirdadosActionPerformed(evt);
            }
        });

        lSenhaDados.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lSenhaDados.setForeground(new java.awt.Color(0, 0, 0));
        lSenhaDados.setText("Senha:");

        lEmailDados.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lEmailDados.setForeground(new java.awt.Color(0, 0, 0));
        lEmailDados.setText("E-mail:");

        lTelefoneDados.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lTelefoneDados.setForeground(new java.awt.Color(0, 0, 0));
        lTelefoneDados.setText("Telefone:");

        lCnpjDados.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lCnpjDados.setForeground(new java.awt.Color(0, 0, 0));
        lCnpjDados.setText("CNPJ:");

        lEmpresaDados.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lEmpresaDados.setForeground(new java.awt.Color(0, 0, 0));
        lEmpresaDados.setText("Nome da empresa:");

        bVoltar.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMeusdadosLayout = new javax.swing.GroupLayout(pMeusdados);
        pMeusdados.setLayout(pMeusdadosLayout);
        pMeusdadosLayout.setHorizontalGroup(
            pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMeusdadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lMeusdados)
                .addGap(138, 138, 138))
            .addGroup(pMeusdadosLayout.createSequentialGroup()
                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMeusdadosLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pMeusdadosLayout.createSequentialGroup()
                                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lEmpresaDados)
                                    .addComponent(lCnpjDados))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tEmpresaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tCnpjDados, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pMeusdadosLayout.createSequentialGroup()
                                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pMeusdadosLayout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(lTelefoneDados))
                                    .addComponent(lEmailDados, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lSenhaDados, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tTelefoneDados, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tEmailDados, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tSenhaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pMeusdadosLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(bAtualizardados))
                            .addGroup(pMeusdadosLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(bExcluirdados, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pMeusdadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bVoltar)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        pMeusdadosLayout.setVerticalGroup(
            pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMeusdadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMeusdados)
                .addGap(49, 49, 49)
                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEmpresaDados)
                    .addComponent(tEmpresaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCnpjDados)
                    .addComponent(tCnpjDados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefoneDados)
                    .addComponent(tTelefoneDados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEmailDados)
                    .addComponent(tEmailDados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pMeusdadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSenhaDados)
                    .addComponent(tSenhaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(bAtualizardados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bExcluirdados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(bVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(pMeusdados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pMeusdados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAtualizardadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizardadosActionPerformed
        

    }//GEN-LAST:event_bAtualizardadosActionPerformed

    private void bExcluirdadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirdadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bExcluirdadosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        metodos met = new metodos();
        usuario user = met.consultaUsuario(this.codigo);
        tEmpresaDados.setText(user.getNomeEmpresa());
    }//GEN-LAST:event_formWindowOpened

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        fecharJanela();
        telaMenu pi = new telaMenu();/*abre telaMenu*/
        pi.setVisible(true);
    }//GEN-LAST:event_bVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaMeusdados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizardados;
    private javax.swing.JButton bExcluirdados;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel lCnpjDados;
    private javax.swing.JLabel lEmailDados;
    private javax.swing.JLabel lEmpresaDados;
    private javax.swing.JLabel lMeusdados;
    private javax.swing.JLabel lSenhaDados;
    private javax.swing.JLabel lTelefoneDados;
    private javax.swing.JPanel pMeusdados;
    private javax.swing.JPasswordField tCnpjDados;
    private javax.swing.JPasswordField tEmailDados;
    private javax.swing.JPasswordField tEmpresaDados;
    private javax.swing.JPasswordField tSenhaDados;
    private javax.swing.JPasswordField tTelefoneDados;
    // End of variables declaration//GEN-END:variables
}
