package telas;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

public class telaFormulario extends javax.swing.JFrame {
    
    public void fecharJanela(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    public telaFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFormulario = new javax.swing.JPanel();
        lFormulario2 = new javax.swing.JLabel();
        lPergunta1 = new javax.swing.JLabel();
        lPergunta2 = new javax.swing.JLabel();
        tPergunta1 = new javax.swing.JPasswordField();
        tPergunta2 = new javax.swing.JPasswordField();
        bEnviarFormulario = new javax.swing.JButton();
        lPergunta4email = new javax.swing.JLabel();
        tPergunta3 = new javax.swing.JPasswordField();
        tPergunta4nome = new javax.swing.JPasswordField();
        lPergunta41 = new javax.swing.JLabel();
        lFormulario1 = new javax.swing.JLabel();
        lSenha2 = new javax.swing.JLabel();
        tlPergunta4email = new javax.swing.JPasswordField();
        lPergunta3 = new javax.swing.JLabel();
        lPergunta4nome = new javax.swing.JLabel();
        bVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pFormulario.setBackground(new java.awt.Color(211, 242, 238));
        pFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pFormulario.setToolTipText("");

        lFormulario2.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lFormulario2.setForeground(new java.awt.Color(0, 0, 0));
        lFormulario2.setText("mais sobre você!");

        lPergunta1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lPergunta1.setForeground(new java.awt.Color(0, 0, 0));
        lPergunta1.setText("Quais sistemas utilizam atualmente na empresa?");

        lPergunta2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lPergunta2.setForeground(new java.awt.Color(0, 0, 0));
        lPergunta2.setText("Se não todas, quais ou qual área pretende modernizar?");

        bEnviarFormulario.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        bEnviarFormulario.setActionCommand("Enviar");
        bEnviarFormulario.setLabel("Enviar");
        bEnviarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarFormularioActionPerformed(evt);
            }
        });

        lPergunta4email.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lPergunta4email.setForeground(new java.awt.Color(0, 0, 0));
        lPergunta4email.setText("E-mail:");

        lPergunta41.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lPergunta41.setForeground(new java.awt.Color(0, 0, 0));
        lPergunta41.setText("Qual o nome e e-mail do responsável pelo acompanhamento das");
        lPergunta41.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lFormulario1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        lFormulario1.setForeground(new java.awt.Color(0, 0, 0));
        lFormulario1.setText("Deixe-nos saber um pouco");
        lFormulario1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lSenha2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lSenha2.setForeground(new java.awt.Color(0, 0, 0));
        lSenha2.setText("melhorias à serem implementadas pela CEGL Solutions ?");

        lPergunta3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lPergunta3.setForeground(new java.awt.Color(0, 0, 0));
        lPergunta3.setText("Quais os principais problemas encontrados hoje na empresa/área? ");

        lPergunta4nome.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        lPergunta4nome.setForeground(new java.awt.Color(0, 0, 0));
        lPergunta4nome.setText("Nome:");

        bVoltar.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFormularioLayout = new javax.swing.GroupLayout(pFormulario);
        pFormulario.setLayout(pFormularioLayout);
        pFormularioLayout.setHorizontalGroup(
            pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioLayout.createSequentialGroup()
                .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pFormularioLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(bEnviarFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pFormularioLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lSenha2)
                            .addComponent(lPergunta41)
                            .addComponent(lPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPergunta1)
                            .addComponent(lPergunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPergunta3)
                            .addComponent(tPergunta2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioLayout.createSequentialGroup()
                                .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lPergunta4email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lPergunta4nome, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tPergunta4nome, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                                    .addComponent(tlPergunta4email))))))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(pFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioLayout.createSequentialGroup()
                                .addComponent(lFormulario1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(235, 235, 235))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioLayout.createSequentialGroup()
                                .addComponent(lFormulario2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(294, 294, 294))))
                    .addGroup(pFormularioLayout.createSequentialGroup()
                        .addComponent(bVoltar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pFormularioLayout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(lPergunta3)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );
        pFormularioLayout.setVerticalGroup(
            pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lFormulario1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lFormulario2)
                .addGap(57, 57, 57)
                .addComponent(lPergunta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lPergunta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPergunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tPergunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lPergunta41, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSenha2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPergunta4nome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPergunta4nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlPergunta4email, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPergunta4email))
                .addGap(56, 56, 56)
                .addComponent(bEnviarFormulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(bVoltar)
                .addContainerGap())
            .addGroup(pFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormularioLayout.createSequentialGroup()
                    .addContainerGap(448, Short.MAX_VALUE)
                    .addComponent(lPergunta3)
                    .addGap(426, 426, 426)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bEnviarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarFormularioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEnviarFormularioActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        fecharJanela();
        telaMenu pi = new telaMenu();/*abre telaMenu*/
        pi.setVisible(true);
    }//GEN-LAST:event_bVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFormulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFormulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFormulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFormulario1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviarFormulario;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel lFormulario1;
    private javax.swing.JLabel lFormulario2;
    private javax.swing.JLabel lPergunta1;
    private javax.swing.JLabel lPergunta2;
    private javax.swing.JLabel lPergunta3;
    private javax.swing.JLabel lPergunta41;
    private javax.swing.JLabel lPergunta4email;
    private javax.swing.JLabel lPergunta4nome;
    private javax.swing.JLabel lSenha2;
    private javax.swing.JPanel pFormulario;
    private javax.swing.JPasswordField tPergunta1;
    private javax.swing.JPasswordField tPergunta2;
    private javax.swing.JPasswordField tPergunta3;
    private javax.swing.JPasswordField tPergunta4nome;
    private javax.swing.JPasswordField tlPergunta4email;
    // End of variables declaration//GEN-END:variables
}
